version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sykell-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sykell_crawler
      MYSQL_USER: sykell
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: sykell-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sykell-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "sykell:password@tcp(mysql:3306)/sykell_crawler?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_URL: "redis:6379"
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      FRONTEND_URL: "http://localhost:5173"
      PORT: "8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 10s
      retries: 3

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: sykell-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     VITE_API_URL: "http://localhost:8080/api/v1"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

volumes:
  mysql_data:
